export const formStyles = {
  page: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingTop: '40px',
  },
  card: {
    background: '#1a1d2e',
    border: '1px solid #2d3748',
    borderRadius: '12px',
    padding: '40px',
    width: '100%',
    maxWidth: '440px',
  },
  title: {
    fontSize: '24px',
    fontWeight: 700,
    color: '#e2e8f0',
    marginBottom: '6px',
  },
  subtitle: {
    color: '#718096',
    marginBottom: '24px',
    fontSize: '14px',
  },
  hint: {
    background: '#2d3748',
    border: '1px solid #4a5568',
    borderRadius: '8px',
    padding: '12px 16px',
    marginBottom: '24px',
    fontSize: '13px',
    color: '#a0aec0',
    lineHeight: '1.6',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  label: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#a0aec0',
    marginBottom: '-8px',
  },
  input: {
    background: '#0f1117',
    border: '1px solid #2d3748',
    borderRadius: '8px',
    padding: '10px 14px',
    color: '#e2e8f0',
    fontSize: '14px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  btn: {
    background: '#3182ce',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '15px',
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: '8px',
    transition: 'background 0.2s',
  },
  btnDanger: {
    background: '#e53e3e',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  btnSuccess: {
    background: '#38a169',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  error: {
    background: '#742a2a',
    border: '1px solid #e53e3e',
    borderRadius: '8px',
    padding: '10px 14px',
    color: '#fc8181',
    fontSize: '13px',
  },
  success: {
    background: '#1c4532',
    border: '1px solid #38a169',
    borderRadius: '8px',
    padding: '10px 14px',
    color: '#68d391',
    fontSize: '13px',
  },
  footer: {
    textAlign: 'center',
    marginTop: '20px',
    fontSize: '13px',
    color: '#718096',
  },
}
